### PR TITLE
Issue #34: reinstate ivy and not download test dependencies

### PR DESCRIPTION
**Pull request by rnveach**
Issue #34

Fix was found at https://stackoverflow.com/questions/5640094/keep-ivy-from-including-test-dependencies

### CODE REVIEW

**Comment by rnveach** [comment]
My local fails with:
````
resolve:
[ivy:retrieve] :: Apache Ivy 2.5.0 - 20191020104435 :: https://ant.apache.org/ivy/ ::
[ivy:retrieve] :: loading settings :: file = M:\checkstyleWorkspaceEclipse\checkstyle-samples\ant-project\ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: com.github.sevntu-checkstyle#sample;working@DESKTOP-91SPF4E
[ivy:retrieve]  confs: [compile]
[ivy:retrieve]  found com.puppycrawl.tools#checkstyle;10.3.4 in public
[ivy:retrieve]  found info.picocli#picocli;4.6.3 in local-maven-2
[ivy:retrieve]  found org.antlr#antlr4-runtime;4.11.1 in local-maven-2
[ivy:retrieve]  found commons-beanutils#commons-beanutils;1.9.4 in local-maven-2
[ivy:retrieve]  found commons-logging#commons-logging;1.2 in local-maven-2
[ivy:retrieve]  found commons-collections#commons-collections;3.2.2 in local-maven-2
[ivy:retrieve]  found com.google.guava#guava;31.1-jre in local-maven-2
[ivy:retrieve]  found com.google.guava#failureaccess;1.0.1 in local-maven-2
[ivy:retrieve]  found com.google.guava#listenablefuture;9999.0-empty-to-avoid-conflict-with-guava in local-maven-2
[ivy:retrieve]  found com.google.code.findbugs#jsr305;3.0.2 in local-maven-2
[ivy:retrieve]  found com.google.errorprone#error_prone_annotations;2.11.0 in local-maven-2
[ivy:retrieve]  found com.google.j2objc#j2objc-annotations;1.3 in local-maven-2
[ivy:retrieve]  found org.reflections#reflections;0.10.2 in local-maven-2
[ivy:retrieve]  found org.javassist#javassist;3.28.0-GA in local-maven-2
[ivy:retrieve]  found org.slf4j#slf4j-api;1.7.32 in local-maven-2
[ivy:retrieve]  found net.sf.saxon#Saxon-HE;11.4 in local-maven-2
[ivy:retrieve]  found org.xmlresolver#xmlresolver;4.4.3 in local-maven-2
[ivy:retrieve]  found org.checkerframework#checker-qual;3.25.0 in local-maven-2
[ivy:retrieve]  found com.github.sevntu-checkstyle#sevntu-checks;1.42.0 in local-maven-2
[ivy:retrieve]  found com.google.code.findbugs#annotations;3.0.1 in local-maven-2
[ivy:retrieve]  found net.jcip#jcip-annotations;1.0 in local-maven-2
[ivy:retrieve] :: resolution report :: resolve 440ms :: artifacts dl 138ms
[ivy:retrieve]  :: evicted modules:
[ivy:retrieve]  com.google.code.findbugs#jsr305;3.0.1 by [com.google.code.findbugs#jsr305;3.0.2] in [compile]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      compile     |   22  |   0   |   0   |   1   ||   19  |   0   |
        ---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: com.github.sevntu-checkstyle#sample
[ivy:retrieve]  confs: [compile]
[ivy:retrieve]  19 artifacts copied, 0 already retrieved (10925kB/56ms)

init-checkstyle:
  [taskdef] Could not load definitions from resource com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties. It could not be found.

checkstyle:

BUILD FAILED
M:\checkstyleWorkspaceEclipse\checkstyle-samples\ant-project\build.xml:20: Problem: failed to create task or type checkstyle
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.
````

Because checkstyle JAR is missing from `lib` folder. I see it being downloaded above, so not sure why it is missing.

**Review by romani — APPROVED** [review]
Awesome

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/com/puppycrawl/tools/checkstyle/ant/checkstyle-ant-task.properties

**Comment by rnveach** [comment]
@romani See my comment at https://github.com/sevntu-checkstyle/checkstyle-samples/pull/45#issuecomment-1275269142.
> Because checkstyle JAR is missing from lib folder. I see it being "found" above, so not sure why it is missing. Sevntu is also missing. I do not see either downloaded in my m2 folder

It is like it is downloading only the sub-dependencies, and ignoring the declared dependency.

**Comment by rnveach** [comment]
@romani CI is "fixed"

**Pull request merged**
